name: Manual Auth Test

# цЙЛхЛХхоЯшбМх░ВчФиуБоуВ╖уГ│уГЧуГлуБкуГпуГ╝уВпуГХуГнуГ╝
on:
  workflow_dispatch:

jobs:
  test-auth:
    runs-on: ubuntu-latest
    name: Run Authentication Test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Decode Service Account JSON
      env:
        TEST_BASE64: ${{ secrets.TEST_GOOGLE_SERVICE_ACCOUNT_JSON_BASE64 }}
        PROD_BASE64: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON_BASE64 }}
      run: |
        # уГЖуВ╣уГИчТ░хвГуБошкНши╝уГХуВбуВдуГлуВТуГЗуВ│уГ╝уГЙ
        if [ -n "$TEST_BASE64" ]; then
          echo "уГЖуВ╣уГИчТ░хвГуБошкНши╝уГХуВбуВдуГлуВТуГЗуВ│уГ╝уГЙф╕н..."
          echo "$TEST_BASE64" | base64 -d > test_service_account.json
          echo "TEST_GOOGLE_SERVICE_ACCOUNT_JSON=test_service_account.json" >> $GITHUB_ENV
        fi
        
        # цЬмчХкчТ░хвГуБошкНши╝уГХуВбуВдуГлуВТуГЗуВ│уГ╝уГЙ
        if [ -n "$PROD_BASE64" ]; then
          echo "цЬмчХкчТ░хвГуБошкНши╝уГХуВбуВдуГлуВТуГЗуВ│уГ╝уГЙф╕н..."
          echo "$PROD_BASE64" | base64 -d > service_account.json
          echo "GOOGLE_SERVICE_ACCOUNT_JSON=service_account.json" >> $GITHUB_ENV
        fi
    
    - name: Show Environment Info
      run: |
        echo "================================"
        echo "чТ░хвГхдЙцХ░уБошинхоЪчК╢ц│Б"
        echo "================================"
        echo "GitHub Actions: Yes"
        echo "Python Version: $(python --version)"
        echo ""
        echo "шинхоЪуБХуВМуБжуБДуВЛчТ░хвГхдЙцХ░:"
        if [ -n "${{ secrets.TEST_GOOGLE_SHEET_NAME }}" ]; then
          echo "тЬЕ TEST_GOOGLE_SHEET_NAME: шинхоЪц╕ИуБ┐"
        else
          echo "тЭМ TEST_GOOGLE_SHEET_NAME: цЬкшинхоЪ"
        fi
        if [ -n "${{ secrets.TEST_GOOGLE_SERVICE_ACCOUNT_JSON_BASE64 }}" ]; then
          echo "тЬЕ TEST_GOOGLE_SERVICE_ACCOUNT_JSON_BASE64: шинхоЪц╕ИуБ┐"
        else
          echo "тЭМ TEST_GOOGLE_SERVICE_ACCOUNT_JSON_BASE64: цЬкшинхоЪ"
        fi
        if [ -n "${{ secrets.GOOGLE_SHEET_NAME }}" ]; then
          echo "тЬЕ GOOGLE_SHEET_NAME: шинхоЪц╕ИуБ┐"
        else
          echo "тЭМ GOOGLE_SHEET_NAME: цЬкшинхоЪ"
        fi
        if [ -n "${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON_BASE64 }}" ]; then
          echo "тЬЕ GOOGLE_SERVICE_ACCOUNT_JSON_BASE64: шинхоЪц╕ИуБ┐"
        else
          echo "тЭМ GOOGLE_SERVICE_ACCOUNT_JSON_BASE64: цЬкшинхоЪ"
        fi
        echo "================================"
    
    - name: Run Authentication Test
      env:
        # уГЖуВ╣уГИчТ░хвГ
        TEST_GOOGLE_SHEET_NAME: ${{ secrets.TEST_GOOGLE_SHEET_NAME }}
        TEST_GOOGLE_SERVICE_ACCOUNT_JSON_BASE64: ${{ secrets.TEST_GOOGLE_SERVICE_ACCOUNT_JSON_BASE64 }}
        # цЬмчХкчТ░хвГ
        GOOGLE_SHEET_NAME: ${{ secrets.GOOGLE_SHEET_NAME }}
        GOOGLE_SERVICE_ACCOUNT_JSON_BASE64: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON_BASE64 }}
      run: |
        echo "ЁЯЪА шкНши╝уГЖуВ╣уГИуВТхоЯшбМуБЧуБ╛уБЩ..."
        python tests/auth_tests/test_google_sheets_auth.py